Feature recordlines n
cortezaproject/corteza-js pull request #18
Opened 2020-06-02 16:54 UTC by tjerman

2020-06-02 16:59 UTC, darh requested changes
minor stuff

2020-06-02 16:59 UTC, darh commented on src/compose/types/page-block/record-list.ts
> +  inlineEditor: boolean;
this is always implicit when editFields are there or any of draggable, positionField, parentField is set, correct?
anyhow, if it really needs to stay, `editable` might be better (so, same as `draggable`)

2020-06-02 16:59 UTC, darh commented on src/compose/types/page-block/record-list.ts
> +  editFields?: unknown[];
move this down under // record-lines

2020-06-02 16:59 UTC, darh commented on src/compose/types/page-block/record-list.ts
> +  parentField?: string;
not loving this "parent"... "refField"? this way we use the same terminology...

2020-06-03 10:32 UTC, tjerman commented
Merged

2020-06-03 10:32 UTC, closed without merging