2023.3.x feature compose blocks auto refresh
cortezaproject/corteza-js pull request #73
Opened 2022-11-02 13:58 UTC by EmmyMay

2022-11-02 14:15 UTC, EmmyMay commented
![](https://github.trello.services/images/mini-trello-icon.png) [Compose page block auto-refresh configurator](https://trello.com/c/I2ToNlOD/3313-compose-page-block-auto-refresh-configurator)

2022-11-02 14:15 UTC, EmmyMay commented
![](https://github.trello.services/images/mini-trello-icon.png) [Compose page block auto-refresh configurator](https://trello.com/c/I2ToNlOD/3313-compose-page-block-auto-refresh-configurator)

2022-11-03 13:53 UTC, Fajfa requested changes

2022-11-03 13:53 UTC, Fajfa commented on src/compose/types/module-field/select.ts
> +  refreshRate: number;
Remove this file

2022-11-03 13:53 UTC, Fajfa commented on src/compose/types/page-block/record-revisions.ts
> +  refreshRate: 0
Lint your code before committing!

2022-11-15 14:26 UTC, Fajfa commented on src/compose/types/page-block/progress.ts
> +    Apply(this.options, o, Number, 'refreshRate')
After the !o return line!
Also double check for same problem in other files you changed. 

Apply should be one after the other and right after the !o return line

2022-11-16 10:58 UTC, Fajfa approved these changes

2022-11-16 17:28 UTC, closed without merging