2023.3.x feature open compose record in modal
cortezaproject/corteza-js pull request #76
Opened 2022-11-11 12:14 UTC by yonkov

2022-11-14 16:07 UTC, Fajfa approved these changes
Almost

2022-11-14 16:08 UTC, Fajfa commented on src/compose/types/page-block/record-list.ts
> -      'openInNewTab',
You need to remove openInNewTab in other places aswell

2022-11-14 16:09 UTC, Fajfa requested changes

2022-11-14 16:09 UTC, Fajfa commented on src/compose/types/page-block/record-list.ts
> -      'openInNewTab',
You need to remove openInNewTab in other places aswell!

2022-11-15 10:23 UTC, yonkov commented on src/compose/types/page-block/record-list.ts
> -      'openInNewTab',
I tried but it is breaking the backwards compatibility with the old checkbox (it is not respected anymore). I ran into two issues trying to remove the `openInNewTab` prop:
1. In it if check `if (o.openInNewTab)` i got TS error: "semantic error TS2339: Property 'openInNewTab' does not exist on type 'Partial<Options>"
2. In the same if check, if I disable ts checks, I always get undefined (value is not respected).

2022-11-15 13:59 UTC, Fajfa commented on src/compose/types/page-block/record-list.ts
> -      'openInNewTab',
You're right, keep it like this but add a comment above so we know that it is legacy

2022-11-16 16:28 UTC, closed without merging

2022-11-16 16:28 UTC, yonkov commented
Closed due to Monorepo Migration