Add support for metric post-proc functions
cortezaproject/corteza-js pull request #9
Opened 2020-05-04 14:42 UTC by tjerman

This allows us to perform simpler operations on end data, such as creating cumulative charts.

2020-05-04 17:57 UTC, darh requested changes

2020-05-04 17:57 UTC, darh commented on src/compose/types/chart/index.ts
> +  prepData ({ labels, metrics }: { labels?: Array<string>; metrics?: Array<Array<number>> } = {}, base: any = {}, postProcFx: (n: number, m: undefined|number, ds: any) => number) {
this interface just got a bit too fat... might be smart if you extract it?

2020-05-04 17:57 UTC, darh commented on src/compose/types/chart/index.ts
> +      // Dataset post process function
looks like magic, a bit more verbose comment?

2020-05-04 17:57 UTC, darh commented on src/compose/types/chart/index.ts
> +const defaultFx = 'n'
n?

2020-05-09 06:55 UTC, darh commented
where are we with this?

2020-05-14 10:41 UTC, tjerman commented
Included with https://github.com/cortezaproject/corteza-js/pull/13

2020-05-14 10:41 UTC, closed without merging